language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: 935a44ecd02fe4e201f2d689ce91857a6d07a857a1ad4ef4508847778fd8555d

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info